import = ["/Users/arkinmodi/.config/alacritty/colours/ayu-dark.toml"]
live_config_reload = true
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[keyboard]
bindings = [
  {chars = " ", key = "Space", mods = "Alt"},
  {chars = "\u0015", key = "Back", mods = "Super"}, # delete word/line
  {chars = "\u001BOF", key = "Right", mode = "AppCursor", mods = "Command"}, # End
  {chars = "\u001BOH", key = "Left", mode = "AppCursor", mods = "Command"}, # Home
  {chars = "\u001Bb", key = "Left", mods = "Alt"}, # one word left
  {chars = "\u001Bf", key = "Right", mods = "Alt"}, # one word right
  {chars = "\u001Bh", key = "H", mods = "Alt"},
  {chars = "\u001Bj", key = "J", mods = "Alt"},
  {chars = "\u001Bk", key = "K", mods = "Alt"},
  {chars = "\u001Bl", key = "L", mods = "Alt"},
]

[window]
decorations = "transparent"
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 110
lines = 35

[window.padding]
x = 10
y = 30
