import = ["/Users/arkinmodi/.config/alacritty/colours/ayu-dark.toml"]
live_config_reload = true
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[keyboard]
bindings = [
  {key = "Space", mods = "Alt", chars = " "},
  {key = "Back", mods = "Super", chars = "\u0015"}, # delete word/line
  {key = "Left", mods = "Alt", chars = "\u001Bb"}, # one word left
  {key = "Right", mods = "Alt", chars = "\u001Bf"}, # one word right
  {key = "Left", mods = "Command", chars = "\u001BOH", mode = "AppCursor"}, # Home
  {key = "Right", mods = "Command", chars = "\u001BOF", mode = "AppCursor"}, # End
  {key = "J", mods = "Alt", chars = "\u001Bj"},
  {key = "K", mods = "Alt", chars = "\u001Bk"},
  {key = "H", mods = "Alt", chars = "\u001Bh"},
  {key = "L", mods = "Alt", chars = "\u001Bl"}
]

[window]
decorations = "transparent"
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 110
lines = 35

[window.padding]
x = 10
y = 30
