#!/usr/bin/env zsh
# shellcheck shell=bash

# This file is the generated by the following command on an Apple Silicon Mac:
# /opt/homebrew/bin/brew shellenv

export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
# shellcheck disable=SC2034
fpath[1,0]="/opt/homebrew/share/zsh/site-functions";
export FPATH;
[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

# eval "$(/usr/bin/env PATH_HELPER_ROOT="/opt/homebrew" /usr/libexec/path_helper -s)"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
