#!/usr/bin/env node

const http = require("http");

const port = process.argv[2] || 8000;
console.log(`Starting server on port ${port}.`);

const server = http.createServer(async (req, res) => {
    console.log(req.method, req.url);

    for (const h in req.headers) {
        console.log(`${h}: ${req.headers[h]}`);
    }

    let body = "";
    req.on("data", (chuck) => (body += chuck));
    req.on("end", () => console.log(body + "\n"));

    if (req.method === "OPTIONS") {
        res.writeHead(200, {
            "access-control-allow-headers":
                req.headers["access-control-request-headers"] ?? "",
            "access-control-allow-origin": "*",
            "content-type": "application/json",
        });
        res.end();
        return;
    }

    await new Promise((r) => setTimeout(r, 1000));

    res.writeHead(200, {
        "access-control-allow-headers":
            req.headers["access-control-request-headers"] ?? "",
        "access-control-allow-origin": "*",
        "content-type": "application/json",
    });
    res.end(JSON.stringify({ message: "Hello World" }));
});

server.listen(port);
