#!/usr/bin/env zsh
# shellcheck shell=bash

set -euo pipefail

TITLE='Terminal'
MESSAGE=$*

PLATFORM=$(uname)
if [[ $PLATFORM == 'Darwin' ]]; then
    # Sounds located in
    # - ~/Library/Sounds
    # - /System/Library/Sounds

    SOUND_NAME='Ping'

    osascript -e 'display notification "'"$MESSAGE"'" with title "'"$TITLE"'" sound name "'"$SOUND_NAME"'"'

elif [[ $PLATFORM == 'Linux' ]]; then
    notify-send "$TITLE" "$MESSAGE"
fi
