#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess

# 1Password Secret Reference Format
# op://<vault-name>/<item-name>[/<section-name>]/<field-name>


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--output-file',
        default='.env',
        help='file to write to (defaults to ".env")',
    )
    parser.add_argument(
        '--section-name',
        default='Environment Variables',
        help='1password section name (defaults to "Environment Variables")',
    )
    parser.add_argument('item_name', nargs=1)
    args = parser.parse_args()

    op_item_info_json = subprocess.run(
        ['op', 'item', 'get', args.item_name[0], '--format', 'json'],
        capture_output=True,
    )
    op_item_info = json.loads(op_item_info_json.stdout)

    envs = {}
    if 'fields' in op_item_info:
        for field in op_item_info['fields']:
            if (
                'section' in field and
                'label' in field['section'] and
                field['section']['label'] == args.section_name and
                'label' in field and
                'reference' in field
            ):
                envs[field['label']] = field['reference']

    with open(args.output_file, 'a') as f:
        for key, value in envs.items():
            f.write(f'{key}="{value}"\n')

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
