#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
import webbrowser


def get_url(remote: str) -> str:
    git_url = subprocess.run(
        ['git', 'remote', 'get-url', remote],
        capture_output=True,
        encoding='UTF-8',
    ).stdout.strip()

    if git_url.startswith('http'):
        return git_url.removesuffix('.git')
    else:
        _, domain, repo = re.split('@|:', git_url)
        repo = repo.removesuffix('.git')
        return f'https://{domain}/{repo}'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('-w', '--web', action='store_true')
    parser.add_argument('-r', '--remote', default='origin')
    args = parser.parse_args()

    url = get_url(args.remote)
    print(url)

    if args.web:
        webbrowser.open_new_tab(url)

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
