#!/usr/bin/env zsh
# shellcheck shell=bash

set -euo pipefail

SEARCH_DIRS=(
    ~/code
    ~/code/sandbox
    ~/Downloads
    ~/Desktop
    ~
)

if [[ $# -eq 1 ]]; then
    dest_dir=$1
else
    dest_dir=$(
        find \
        "${SEARCH_DIRS[@]}" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        | fzf \
        --preview '
            onefetch {} \
            --type programming markup prose data \
            --exclude package-lock.json \
            --disabled-fields churn authors contributors \
            --no-title \
            2> /dev/null \
            || ls -la --color=always {}
        ' \
        --preview-window 'up'
    )
fi

if [[ -z "$dest_dir" ]]; then
    exit 0
fi

dest_name=$(basename "$dest_dir" | tr . _)

if [[ ! -v TMUX ]]; then
    # we are not inside tmux
    tmux new-session -A -c "$dest_dir" -s "$dest_name"
    exit 0

elif ! tmux has-session -t "$dest_name" &> /dev/null; then
    tmux new-session -d -c "$dest_dir" -s "$dest_name"
fi

tmux switch-client -t "$dest_name"
