#!/usr/bin/env bash

set -euo pipefail

function printUsage() {
    USAGE=$(cat << EOF
usage: tmux-runner [-h] -s SESSION_DIRECTORY SHELL_COMMAND

Run a command in a target session.

positional arguments:
  SHELL_COMMAND         Command to run.

arguments:
  -s SESSION_DIRECTORY  Target session directory.

optional arguments:
  -h, --help            Show this help message and exit.
EOF
    )
    echo "$USAGE"
}

while getopts 'hs:' OPTION; do
    case "$OPTION" in
        h)
            printUsage
            exit 0
            ;;

        s)
            SESSION_DIR="$OPTARG"
            ;;
    esac
done
shift $((OPTIND-1))


if [[ -z "${SESSION_DIR:-}" || $# -le 0 ]]; then
    printUsage
    exit 1
fi

CMD="$*"
SESSION_NAME=$(basename "$SESSION_DIR" | tr . _)

if ! tmux has-session -t="$SESSION_NAME" &> /dev/null; then
    tmux new-session -d -c "$SESSION_DIR" -s "$SESSION_NAME"
fi

tmux new-window -a -d -t "$SESSION_NAME:1" -- "$CMD"
