#!/usr/bin/env bash

set -euo pipefail

uuid=$(uuidgen)

PLATFORM=$(uname)
if [[ $PLATFORM == 'Darwin' ]]; then
    echo -n "$uuid" | pbcopy
elif [[ $PLATFORM == 'Linux' ]]; then
    echo -n "$uuid" | xclip -selection clipboard
fi

echo "Copied uuid to your clipboard" >> /dev/stderr
echo "$uuid"
