#!/usr/bin/env bash

yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config window_gap 3

yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
